#!/bin/bash

#unbuffer comes from the expect package

main() {
    ( exec 2>&1; unbuffer make "${@}"; ) \
    > >( while read line; do
             printf "%(%Y-%m-%dT%H:%M:%S)T %s\n" -1 "${line}"
         done \
         |tee -a br.log \
         |grep --colour=never -E '>>>'
       )
}

main "${@}" && beep
