#!/bin/sh

set -e

if [ $# -ne 1 ]; then
    echo "usage: cherry-pick-release.sh revision"
    exit 1
fi

rev=$(git rev-parse --short "$1")

# prepare commit message
squashmsg="Squashed commit of the following:"
commitfile="$(mktemp)"
git log -1 --format="%s%n%n%b" "$rev" | grep -B99 -m1 "$squashmsg" | sed '$ d' > "$commitfile"
echo "Cherry-pick of $rev." >> "$commitfile"

if ! git cherry-pick -n "$rev"; then
    echo "cherry-pick -n didn't apply cleanly. When you're done, use the following command to commit:"
    echo "    git commit -e -F \"$commitfile\""
    exit 1
fi

ret=0
if ! git commit -e -F "$commitfile"; then
    ret=$?
fi

rm "$commitfile"

exit $ret
