#!/bin/sh

iw dev wlan0 set power_save on
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs';
echo 'min_power' > '/sys/class/scsi_host/host0/link_power_management_policy';
echo '0' > '/proc/sys/kernel/nmi_watchdog';
echo 'auto' > '/sys/bus/i2c/devices/i2c-0/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-10/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-1/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-2/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-3/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-4/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-5/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-6/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-7/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-8/device/power/control';
echo 'auto' > '/sys/bus/i2c/devices/i2c-9/device/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:01.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:01.1/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:14.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:16.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1b.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1c.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1c.2/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1c.3/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1c.4/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:00:1f.3/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:01:00.1/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:03:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:04:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:05:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:06:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:07:00.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:07:03.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:07:04.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:07:05.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:07:06.0/power/control';
echo 'auto' > '/sys/bus/pci/devices/0000:08:00.0/power/control';
echo 'auto' > '/sys/bus/usb/devices/1-12/power/control';
echo 'auto' > '/sys/bus/usb/devices/1-8.1/power/control';
echo 'auto' > '/sys/bus/usb/devices/1-8.2/power/control';
echo 'auto' > '/sys/bus/usb/devices/1-8.3/power/control';
echo 'auto' > '/sys/bus/usb/devices/1-8/power/control';
echo 'auto' > '/sys/bus/usb/devices/2-4/power/control';
echo 'auto' > '/sys/bus/usb/devices/usb1/power/control';
echo 'auto' > '/sys/bus/usb/devices/usb2/power/control';

# Disable auto suspend when a screen is connected. We could use the battery
# status but it's not up-to-date when we are pinging it.
# Leave out HDMI as I don't use it at work so it means a special event which
# require special tunning.
if xrandr | grep 'DP-3 connected' || xrandr | grep 'DP-4 connected'; then
	for usb_dev in /sys/bus/usb/devices/*/; do
		[ ! -f "${usb_dev}/power/control" ] && continue
		echo "on" > "${usb_dev}/power/control"
	done
fi
