#!/bin/sh

for i in /sys/bus/usb/devices/*; do
        [ ! -f $i/idVendor ] && continue
        idVendor=$(cat $i/idVendor)
        idProduct=$(cat $i/idProduct)
        # Typematrix
        if [ "$idVendor" =  "1e54" -a "$idProduct" =  "2030" ]; then
             echo "on" > $i/power/control
        fi
        # Mouse
        if [ "$idVendor" =  "1bcf" -a "$idProduct" =  "0005" ]; then
             echo "on" > $i/power/control
        fi
done
