#!/bin/sh

FEH_ARGS="--randomize"
SCREEN=$(cat /tmp/screen)
if [ "${SCREEN}" = 1 ]; then
        FEH_ARGS="${FEH_ARGS} --bg-max"
else
        FEH_ARGS="${FEH_ARGS} --bg-scale"
fi
feh ${FEH_ARGS} /home/maxime/Documents/perso/wallpaper/
